/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"


int add(CLIENT *clnt, int x, int y) {
	operands ops;
	int * result;
	
	// fills the 'operand' struct to send it as a function argument
	ops.x = x;
	ops.y = y;
	// calls the stub client
	result = add_100(&ops, clnt);
	if ( result == NULL) {
		fprintf(stderr, "Problem calling RPC\n");
		exit(0);
	}
	return(*result);
}


int sub(CLIENT *clnt, int x, int y) {
        operands ops;
        int * result;

        // fills the 'operand' struct to send it as a function argument
        ops.x = x;
        ops.y = y;
        // calls the stub client
        result = sub_100(&ops, clnt);
        if ( result == NULL) {
                fprintf(stderr, "Problem calling RPC\n");
                exit(0);
        }
        return(*result);
}

float divi(CLIENT *clnt, int x, int y) {
        operands ops;
        float * result;

        // fills the 'operand' struct to send it as a function argument
        ops.x = x;
        ops.y = y;
        // calls the stub client
        result = divi_100(&ops, clnt);
        if ( result == NULL) {
                fprintf(stderr, "Problem calling RPC\n");
                exit(0);
        }
        return(*result);
}


int mult(CLIENT *clnt, int x, int y) {
        operands ops;
        int * result;

        // fills the 'operand' struct to send it as a function argument
        ops.x = x;
        ops.y = y;
        // calls the stub client
        result = mult_100(&ops, clnt);
        if ( result == NULL) {
                fprintf(stderr, "Problem calling RPC\n");
                exit(0);
        }
        return(*result);
}



int
main (int argc, char *argv[])
{
	CLIENT * clnt;
	char *host;
	int x, y;
	char operator;

	if (argc < 5) {
		printf ("usage: %s <server_host> <operand 1> <operator> <operand 2>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	clnt = clnt_create(host, PROG, VER, "udp");
	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	x = atoi(argv[2]);
	y = atoi(argv[4]);

	// switch operator
	operator = argv[3][0];
	switch (operator) {
		case '+':
			printf("%d %c %d = %d\n", x, operator, y, add(clnt, x, y));
			break;
		case '-':
			printf("%d %c %d = %d\n", x, operator, y, sub(clnt, x, y));
			break;
		case '*':
			printf("%d %c %d = %d\n", x, operator, y, mult(clnt, x, y));
			break;
		case '/':
			printf("%d %c %d = %f\n", x, operator, y, divi(clnt, x, y));
			break;
		default:
			printf("Wrong operator\n");
	}

exit (0);
}
