/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"

int *
add_100_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;
	
	result = argp->x + argp->y;	

	return &result;
}

int *
sub_100_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x - argp->y;

	return &result;
}

float *
divi_100_svc(operands *argp, struct svc_req *rqstp)
{
	static float  result;

	result = (float)(argp->x) / (float)(argp->y);

	return &result;
}

int *
mult_100_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->x * argp->y;

	return &result;
}
